DROP TABLE PERSON;

/*
DROP TABLE POSSEDIMENTI;
DROP TABLE PERSON;
DROP TABLE UMANO;

 CREATE TABLE UMANO
 ( id int NOT NULL AUTO_INCREMENT,
   anima number(1) NOT NULL,
   PRIMARY KEY (id)
 );

 CREATE TABLE PERSON
 ( id int NOT NULL AUTO_INCREMENT,
   firstName varchar(255) NOT NULL,
   lastName varchar(255) NOT NULL,
   UMANO_ID INT,
   FOREIGN KEY (UMANO_ID) REFERENCES UMANO(id),
   PRIMARY KEY (id)
 );

 CREATE TABLE POSSEDIMENTI
 ( id int NOT NULL AUTO_INCREMENT,
   tipoPossedimenti varchar(255) NOT NULL,
   UMANO_ID INT,
   FOREIGN KEY (UMANO_ID) REFERENCES UMANO(id),
   PRIMARY KEY (id)
 );
*/



